version: '3.9'
services:
  backend:
    build: ./apps/backend
    env_file: .env
    ports:
      - '5000:5000'
  frontend:
    build: ./apps/frontend
    env_file: .env
    ports:
      - '3000:3000'
