version: "3"
services:
  api:
    build:
      context: ..
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "8000:8000"
  web:
    build:
      context: ..
      dockerfile: infra/docker/web.Dockerfile
    ports:
      - "3000:3000"
  worker:
    build:
      context: ..
      dockerfile: infra/docker/worker.Dockerfile
